# Example configuration for user repositories (not in an organization)
# Organization name (can be null if repositories are not in an organization)
organization: null
# List one or more repositories to analyze.
# If organization is null, repositories should be in format "username/repository-name"
# If organization is set, repositories should be just the repository name
repositories:
  - octocat/Hello-World
  - username/my-project
  - another-user/awesome-repo

# List specific branches to analyze, or leave empty for all branches
branches: []

# Optional: Define specific time ranges to analyze.
# If this section is removed or empty, the entire commit history will be analyzed.
time_ranges:
  - name: "Last Month"
    start_date: "2024-01-01"
    end_date: "2024-01-31"
  - name: "Last Quarter"
    start_date: "2023-10-01"
    end_date: "2023-12-31" 